name: test_utils
description: A new Flutter project.
version: 0.0.1
homepage:

environment:
  sdk: '>=2.19.3 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
#  git:
#    url: https://github.com/tolotrasamuel/flutter_utils
#    ref: 4f2ece41104f9c79c6b2ff6533dace19793147f1
  flutter_utils:
    git:
        url: https://github.com/tolotrasamuel/flutter_utils
        ref: 968d1ed22aabf763ff52e1ed5df7a007809a4fd8
# I am going to always take the master branch because
# A project depending on this will need to update this version
# everytime flutter_utils changes
#  UPDATE: nevermind, it does not work. it is worse.
#Because every version of test_utils from git depends on flutter_utils from
#  git https://github.com/tolotrasamuel/flutter_utils at HEAD and pdf_tool depends
#  on flutter_utils from git https://github.com/tolotrasamuel/flutter_utils at
#  968d1ed22aabf763ff52e1ed5df7a007809a4fd8, test_utils from git is forbidden.
# I don't know why
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flame: ^1.6.0
  flame_test: ^1.9.2

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
